import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  projectNames: string[] = [
    "Accommodation & Fare Enquiry",
    "Beneficiary Profile Management",
    "Concession Management",
    "Customer Relationship Management (CRM)",
    "Direct Benefit Transfer (DBT)",
    "E-Catering",
    "HHT",
    "Intermodal Booking",
    "IRCTC",
    "IRCTC Wallet (NGeT)",
    "Metro Ticketing",
    "Next Generation e-Ticketing (NGeT)",
    "NTES",
    "Passenger Amenities",
    "Passenger Helpline (112 / 139)",
    "Passenger Safety",
    "Passenger Segmentation",
    "PRS",
    "RailMadad",
    "Retiring Room",
    "Single Railway Wallet",
    "Travel Insurance",
    "TTE Application",
    "UTS",
    "UTSonMobile",
    "UTS R-Wallet",
    "Web Enabled Coaching Refund System (WECRS)",
    "Tourist Train Booking",
    "Enquiry",
    "Handicapped card management",
    "Fare Management",
    "Loyalty Program",
    "Stock Roll Management",
    "DA-ITP (Ideal Train Profile)",
    "BrownField Application Component",
    "Circular Management",
    "Common Payment Gateway (CPG)",
    "Data Analytics",
    "Data Utilities Handler",
    "E-drishti / Dashboard",
    "Existing Application Component",
    "External Financial bodies",
    "Google Ads",
    "Greenfield Application Component",
    "Indian Railway Market Research and Business Development (IRMRBD)",
    "IT Service management",
    "NATGRID",
    "Parcel Management System (PMS)",
    "PRIMES",
    "Railway Claims Tribunal (RCT)",
    "Rates Branch System (RBS)",
    "RPF Security Management System (RSMS)",
    "Service Agent",
    "SMS Gateway",
    "Socoal Media Applications",
    "UIDAI",
    "UMANG",
    "e-Auction Application",
    "Station Working Rule (SWR) Application",
    "Data Access Component",
    "EP (Lighting On/Off at Station)",
    "IRSPS",
    "WA",
    "FOIS (Freight Operation & Information Systems)",
    "Freight Partner Warehouse",
    "Freight Maintenance Management (FMM)",
    "Workshop Information System",
    "FCMS (Freight Commercial & Management System",
    "External Vendor's Weighment System",
    "Management of Unclaimed Consignment",
    "System for Locomotive Asset Management (SLAM)",
    "SATSANG",
    "ICMS",
    "CMM - Coach Maintenance Module",
    "COA (Control Office Automation)",
    "Integrated Train Disaster Management",
    "Track Management System (TMS)",
    "AIMS (Acounting Information Management System)",
    "EPS (E-Procurement System)",
    "MERS",
    "Money Receipt",
    "Traffic Accounts management System (TAMS)",
    "Goods & Service Tax (GSTM)",
    "ARMS (Accounting Reform Management System)",
    "HRMS",
    "TTE Lobby",
    "Crew Management System (CMS)"
  ];

  dataObjects: string[] = [
    "Aadhar verification information",
    "Accommodation Availability Enquiry data",
    "Accommodation Availability For A Destination",
    "Accomodation Availability details with fare",
    "Accountal of transactions",
    "Agent booking",
    "Agent creation & Operation details",
    "Agent Interface details",
    "Agent Login data",
    "Agents Management Data",
    "All Classes Accommodation Availability Query details",
    "All Classes Fare Enquiry",
    "All Remote Location Charting Status",
    "All Trains For A Destination",
    "Alphabetical list Information",
    "Announcement Data",
    "ATR Status / Report",
    "ATVM Bin Management Data",
    "Authentication Details",
    "Authority booking",
    "Auth PNR Cancellation",
    "Auth PNR Enquiry detail",
    "Availability enquiry data",
    "Balance Sheet Data",
    "Berth Details",
    "Berth Type Wise Information",
    "Beyond and within ARP FT quota booking over the internet",
    "Bi-lingual chart Infromation",
    "Blank Paper Ticket Booking",
    "Block Booking data",
    "Boarding Point change",
    "Booking location Information",
    "Booking Transaction History",
    "Bottom Performance Data",
    "BPT Bulk Booking",
    "Cab Road Ticket",
    "Cancellation / NI data",
    "Cancellation of e-ticket details",
    "Cancellation Of Seat",
    "Captaincy report",
    "Case dealing / Processing",
    "Case Details",
    "Case disposal Details",
    "Case Registration Detail",
    "Case Returned from OS/ Officer-to be Corrected/ Re-processed Re-forwarded to OS Details",
    "Case verification by OS details",
    "Cause Report",
    "Change of boarding point data",
    "Change of passenger name",
    "Change Password details",
    "Chart & Berth Infromation",
    "Chart display",
    "chart display /edit chart",
    "Chart preparation Information",
    "chart printing data",
    "Circular journey fare",
    "Circular Journey Special Cancellation details",
    "Coach Consist Report",
    "Coaching earning Detail",
    "Coach-Wise Passenger Booked data",
    "Coach-wise reading",
    "Communication Preference",
    "Comodity List",
    "Compaction Criteria details for Selection Of Seat/Berth Number",
    "Complaint Assignment Detail",
    "Complaint Detail (Type/ Subtype)",
    "Concessional Fare",
    "Concession Booking Detail",
    "Concession Card Data",
    "Connecting Journey Booking",
    "Contact Information",
    "CR / TR Note",
    "Current Booking Availability",
    "Current Booking Availability - Remote Wise details",
    "Current Booking data",
    "Current booking Information",
    "Current PNR Status Enquiry data",
    "Current Status Of Passengers",
    "Dashboard Data",
    "Date Of Booking And Shift ID",
    "Dealer (re)Allocation Details",
    "Destination cluster",
    "PNR Enquiry / Search",
    "Digital / RWallet Payment Data",
    "Direct reservation",
    "Discounted Fare",
    "Download offset data",
    "DTC Report",
    "Duplicate ticket refund details",
    "EDR Details",
    "Employment Information",
    "Error Sheet",
    "ex-booking list preparation Information",
    "Extension details Of Waiting List",
    "Failed Transaction History",
    "Fare Detail",
    "Fare Enquiry data",
    "Fast Booking Data",
    "Flexi Fare System",
    "Foreign tourist Booking",
    "Foreign tourist canc/enq",
    "Foreign tourist reservation",
    "Forgot Account details",
    "FT within ARP data",
    "General Accommodation Availability Query details",
    "Geo Fencing Data",
    "Grievance Status",
    "GST data",
    "Halt Management Data",
    "Heritage Trains",
    "Hon'ble MP/Ex MP Registration feature provided to secretariat for bulk booking for a constituency",
    "Intermediate Station Details",
    "Invalid Reason",
    "Journey class wise availability",
    "Journey Date change",
    "Journey modification",
    "Journey Quota change",
    "Journal, Error Sheet, Bank Data, Bank Wise Settlement",
    "Last Updated Berth availability",
    "List Of Berth",
    "Login/Signup",
    "Loyalty Discount",
    "Luggage Details",
    "Master Chart",
    "Middle Name / surname splitting",
    "Military Enquiry",
    "Ministry / Officer Booking",
    "Mobile ticketing transaction data",
    "MP and MPSR Booking",
    "NDR ISI report",
    "New Agency Registration",
    "No Chart Prepared",
    "Non Railway Information",
    "NT Booking",
    "NT booking/ cancellation/ Enquiry",
    "NT List",
    "NTCR Note",
    "NTCR Note by date",
    "Ntes Service",
    "OBC Concession Data",
    "Old record",
    "Overall Seat Details",
    "P/Q Quota",
    "Passenger birth chart data",
    "Passenger name and age",
    "Passenger past history",
    "Passenger queries",
    "Pensioner Concession",
    "PNR details",
    "PNR details and PRS details",
    "Prepaid Tax",
    "PRIORITY",
    "PRIT",
    "Promotion",
    "QFC and PFC",
    "Quota data",
    "Quota Master data",
    "Rail Travelers Service",
    "Refund details",
    "Refund ISI report",
    "Refusal Report",
    "Regulation Data",
    "Remaining Accommodation Availability",
    "Remote Location Charting Status",
    "Retaintment of ticket",
    "Re-ticketing",
    "Rider Agreement",
    "RMF Enquiry",
    "Roll Back Information",
    "Rollback Status",
    "Rulebook",
    "Running Room Facilities",
    "SA Application Data",
    "Saving Seat Booking",
    "SCA Audit trail data",
    "Seat Accommodation",
    "Seat Availability Details",
    "Seat Availability Enquiry",
    "Seat Booking And Cancellation Details",
    "Seat Number Status",
    "Security Data",
    "Seperate rule book provision for Commercial Staff and RPF Staff",
    "SMS alert data",
    "Social Welfare Committee booking",
    "Sold Seat Booking",
    "Special Accommodation Availability",
    "Special Class Fare Enquiry",
    "Special Guest",
    "Station Baggage Booking Data",
    "Station code and Details",
    "Station Master And Site Section",
    "Station Table",
    "Stock Keeping Unit",
    "Stoppage Enquiry",
    "Sub-Head Provision",
    "Tatkal booking",
    "Tatkal Charges",
    "Ticket Allocation",
    "Ticket Extension",
    "Ticket Printing",
    "Ticket Refund",
    "Ticket Status",
    "Token data",
    "Top Performing data",
    "Tour Ticket",
    "Tourist Permits",
    "Transaction status",
    "Travel Date/ List of Boarding Points",
    "Traveller's Details",
    "Type Of Booking",
    "U-MIS Data",
    "User Data",
    "User Guide",
    "User Journey Details",
    "User Name and Password data",
    "Utilization Data",
    "Vacant Berth",
    "Verification Process",
    "Wait List Cancellation",
    "Waiting List",
    "Waiting list Extension Data",
    "Wallet details",
    "Window Accommodation Availability",
    "WRG Offet Data"
  ];

  selectedProject: string = '';
  tableVisible: boolean = false;
  rows: any[] = [];
  jsonOutput: string = '';

  showTable() {
    this.tableVisible = true;
  }

  addRow() {
    this.rows.push({
      projectName: this.selectedProject,
      dataReceived: '',
      dataConsumed: '',
      editable: true
    });
  }

  deleteRow(index: number) {
    this.rows.splice(index, 1);
  }

  modifyRow(row: any) {
    row.editable = !row.editable;
  }

  generateJSON() {
    const data: any = {};

    this.rows.forEach(row => {
      if (!data[row.projectName]) {
        data[row.projectName] = {
          projectName: row.projectName,
          dataReceived: {},
          dataConsumed: {}
        };
      }

      const dataReceivedCount = Object.keys(data[row.projectName].dataReceived).length + 1;
      const dataConsumedCount = Object.keys(data[row.projectName].dataConsumed).length + 1;

      data[row.projectName].dataReceived[`dataReceived ${dataReceivedCount}`] = row.dataReceived;
      data[row.projectName].dataConsumed[`dataConsumed ${dataConsumedCount}`] = row.dataConsumed;
    });

    this.jsonOutput = JSON.stringify(data, null, 2);
  }
}
